name: Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: pcov

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Composer
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Execute PHPUnit
      run: vendor/bin/phpunit --coverage-xml=build/coverage-xml

    - name: Upload Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: build/coverage-xml/coverage.xml
